### PR TITLE
Send matqueue data in chunks of 64kb to fix overloading net library, …

### LINKED ISSUE #16: advmat2_sendmatqueue net message fails to send data to clients when serialized data is > 64kb
The reason you get the byteone/bytetwo error from the serialize library is because the encoded json string in the `advmat2_sendmatqueue` message is larger than what the net library can send. Once a few entities with advmat applied are removed and the encoded length drops below 64kb, it works again.

In the `advmat2_readytoreceive` receiver callback, you should probably be sending this data in chunks no larger than 64kb to the requesting client, otherwise existing advmat textures will not be applied for clients that connect when there is > 64kb worth of data to network.

I can explain in more detail if needed.

(I debugged this problem by looking at the JSON-encoded string and looking for abnormalities that might break during serialize/unserialize. Nothing looked wrong. I loaded the data serverside, compressed it, and decompressed it without any issue. I then printed the length of the serialized string and noticed it was ~66kb, which is larger than what net can send per message.)

### PR DESCRIPTION
**Pull request by Mista-Tea**
…use util.Compress and not serialize

Closes #16 

I don't understand the use of the `serialize` library here - the standard `util.Compress` function converts what would be `~66kb` of serialized data into just around `~3kb` of LZMA data. So maybe don't use the serialize library when networking data.

I've tested this on my multiplayer server with several hundred props that have advmat2 applied, and it can now actually network the data to the client properly and load the queue when connecting to the server.

### CODE REVIEW

**Comment by Mista-Tea** [comment]
I didn't realize there are 2 places that are networking serialized data. The other place needs to be fixed as well.

**Comment by Mista-Tea** [comment]
Still need one more commit to chunk the data in the Materialize receiver callback.

**Comment by ZH-Hristov** [comment]
I did try to use just util.Compress the first time, but the string just wouldn't send over the net for some reason.

**Comment by Mista-Tea** [comment]
You need to use net.Read/WriteData, not String, with compressed data.

**Comment by ZH-Hristov** [comment]
I see, thank you.

**Comment by Mista-Tea** [comment]
So, I think I misunderstood how the `Materialize` net message was being used. I thought it was sending one large message like `advmat2_sendmatqueue`, but that is not the case.

As such, we really probably don't have to worry about chunking the data sent in `Materialize` since it'll basically never send 64kb of data for a single entity, especially now that it is compressed.

**I think this is ready to merge now. Feel free to test it out yourself. This should particularly fix:**
- AdvMats not being applied for clients that connect when the advmat data was > 64kb
- AdvMats not applying correctly for some entities when loading dupes due to serialize library issues
- Clients overflowing when duping and respawning an AdvMat-applied dupe(?) - might've just been trying to send far too much data all at once for large dupes

Apart from the fixes, compressing the data should significantly reduce the load on the sever/client network.

**Comment by ZH-Hristov** [comment]
Yeah Materialize's been a single entity thing ever since the original tool and I haven't really touched it, aside from adding in more customizable material shaders.

**Pull request merged**
